import markdown
from agents import CompanyResearcher


HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Company Research Report</title>

<style>
:root {{
  --bg: #0f172a;
  --card: #020617;
  --text: #e5e7eb;
  --muted: #94a3b8;
  --accent: #38bdf8;
  --border: #1e293b;
}}

body {{
  margin: 0;
  padding: 40px;
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
               Inter, Roboto, Helvetica, Arial, sans-serif;
}}

.container {{
  max-width: 900px;
  margin: auto;
}}

.card {{
  background: var(--card);
  border-radius: 14px;
  padding: 40px;
  box-shadow: 0 10px 40px rgba(0,0,0,0.4);
}}

h1 {{
  font-size: 32px;
  margin-bottom: 10px;
}}

.subtitle {{
  color: var(--muted);
  margin-bottom: 30px;
}}

section {{
  margin-top: 40px;
}}

section h2 {{
  border-left: 4px solid var(--accent);
  padding-left: 12px;
  color: var(--accent);
  margin-bottom: 15px;
}}

hr {{
  border: none;
  height: 1px;
  background: var(--border);
  margin: 30px 0;
}}

table {{
  width: 100%;
  border-collapse: collapse;
  margin: 20px 0;
}}

th, td {{
  border: 1px solid var(--border);
  padding: 10px;
  text-align: left;
}}

th {{
  background: #020617;
}}

code {{
  background: #020617;
  padding: 4px 6px;
  border-radius: 6px;
  font-family: monospace;
}}

pre {{
  background: #020617;
  padding: 16px;
  border-radius: 10px;
  overflow-x: auto;
}}

.footer {{
  text-align: center;
  margin-top: 40px;
  color: var(--muted);
  font-size: 13px;
}}
</style>
</head>

<body>
<div class="container">
  <div class="card">

    <h1>Company Research Report</h1>
    <div class="subtitle">
      <b>Company:</b> {company}<br/>
      <b>Industry:</b> {industry}<br/>
      <b>Geography:</b> {geo}<br/>
      <b>Time Horizon:</b> {time}
    </div>

    <hr/>

    {sections}

    <div class="footer">
      Generated by Multi-Agent Research System
    </div>

  </div>
</div>
</body>
</html>
"""


def md_section(title, md_text):
    html = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "toc"]
    )
    return f"""
    <section>
      <h2>{title}</h2>
      {html}
    </section>
    """


def save_html(research: CompanyResearcher, filename="report.html"):
    sections = ""
    sections += md_section("💰 Financials & Regulatory Research", research.financials)
    sections += md_section("📰 News & Media Intelligence", research.news)
    sections += md_section("🤔 Social & Public Sentiment", research.sentiment)
    sections += md_section("🌐 Market & Competitive Context", research.market)
    sections += md_section("✨ Insight Synthesis", research.synthesis)

    html = HTML_TEMPLATE.format(
        company=research.company_name,
        industry=research.industry_focus,
        geo=research.geo_focus,
        time=research.time_horizon,
        sections=sections
    )

    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"📄 HTML report saved: {filename}")
